title: Your awesome title
author:
  name: GitHub User
  email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

markdown: kramdown
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# - about.md

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

kramdown:
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: false
